using System;

namespace BSPLumpManager.BSPReader
{
    public enum LumpType : int
    {
        ENTITIES = 0,
        PLANES,
        TEXDATA,
        VERTEXES,
        VISIBILITY,
        NODES,
        TEXINFO,
        FACES,
        LIGHTING,
        OCCLUSION,
        LEAFS,
        FACEIDS,
        EDGES,
        SURFEDGES,
        MODELS,
        WORLDLIGHTS,
        LEAFFACES,
        LEAFBRUSHES,
        BRUSHES,
        BRUSHSIDES,
        AREAS,
        AREAPORTALS,
        PORTALS,
        UNUSED0,
        PROPCOLLISION,
        CLUSTERS,
        UNUSED1,
        PROPHULLS,
        PORTALVERTS,
        UNUSED2,
        PROPHULLVERTS,
        CLUSERPORTALS,
        UNUSED3,
        PROPTRIS,
        DISPINFO,
        ORIGINALFACES,
        PHYSDISP,
        PHYSCOLLIDE,
        VERTNORMALS,
        VERTNORMALINDICES,
        DISP_LIGHTMAP_ALPHAS,
        DISP_VERTS,
        DISP_LIGHTMAP_SAMPLE_POSITIONS,
        GAME_LUMP,
        LEAFWATERDATA,
        PRIMITIVES,
        PRIMVERTS,
        PRIMINDICES,
        PAKFILE,
        CLIPPORTALVERTS,
        CUBEMAPS,
        TEXDATA_STRING_DATA,
        TEXDATA_STRING_TABLE,
        OVERLAYS,
        LEAFMINDISTTOWTER,
        FACE_MACRO_TEXTURE_INFO,
        DISP_TRIS,
        PHYSCOLLIDESURFACE,
        PROP_BLOB,
        WATEROVERALYS,
        LIGHTMAPPAGES,
        LEAF_AMBIENT_INDEX_HDR,
        LIGHTMAPPAGEINFOS,
        LEAF_AMBIENT_INDEX,
        LIGHTING_HDR,
        WORLDLIGHTS_HDR,
        LEAF_AMBIENT_LIGHTING_HDR,
        LEAF_AMBIENT_LIGHTING,
        XZIPPAKFILE,
        FACES_HDR,
        MAP_FLAGS,
        OVERLAY_FADES,
        OVERLAY_SYSTEM_LEVELS,
        PHYSLEVEL,
        DISP_MULTIBLEND
    }

    [Flags]
    public enum BrushContents : int
    {
        EMPTY = 0,
        SOLID = 0x1,
        WINDOW = 0x2,
        AUX = 0x4,
        GRATE = 0x8,
        SLIME = 0x10,
        WATER = 0x20,
        MIST = 0x40,
        OPAQUE = 0x80,
        TESTFOGVOLUME = 0x100,
        UNUSED = 0x200,
        UNUSED6 = 0x400,
        TEAM1 = 0x800,
        TEAM2 = 0x1000,
        IGNORE_NODRAW_OPAQUE = 0x2000,
        MOVEABLE = 0x4000,
        AREAPORTAL = 0x8000,
        PLAYERCLIP = 0x10000,
        MONSTERCLIP = 0x20000,
        CURRENT_0 = 0x40000,
        CURRENT_90 = 0x80000,
        CURRENT_180 = 0x100000,
        CURRENT_270 = 0x200000,
        CURRENT_UP = 0x400000,
        CURRENT_DOWN = 0x800000,
        ORIGIN = 0x1000000,
        MONSTER = 0x2000000,
        DEBRIS = 0x4000000,
        DETAIL = 0x8000000,
        TRANSLUCENT = 0x10000000,
        LADDER = 0x20000000,
        HITBOX = 0x40000000
    }
}
